language: c
before_install: source ./.travis-ocaml.sh
install:
  - ocamlc -version
  - opam --version
  - opam install ocamlfind ounit
script:
  - make
  - make test
  - make install
  - make installtest
cache: apt
env:
  - OCAML_VERSION=4.1
  - OCAML_VERSION=4.0
  - OCAML_VERSION=3.12
