language: c
before_install: source ./.install-ocaml.sh
install: opam install ocamlfind ounit
before_script:
  - ocamlc -version
  - opam --version
script:
  - make
  - make test
  - make install
  - make install-test
cache: apt
env:
  - OCAML_VERSION=4.1
  - OCAML_VERSION=4.0
  - OCAML_VERSION=3.12
